// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"task_managerv2/bootstrap"
	"task_managerv2/delivery/controllers"
	"task_managerv2/delivery/router"
	"task_managerv2/repository"
	"task_managerv2/usecase"
)

// Injectors from wire.go:

func InitializeRouter() router.Router {
	database := bootstrap.InitMongoDB()
	taskRepository := repository.InitTaskRepository(database)
	taskUsecase := usecase.InitTaskUsecase(taskRepository)
	taskController := controllers.InitTaskController(taskUsecase)
	userRepository := repository.InitUserRepository(database)
	userUsecase := usecase.InitUserUsecase(userRepository)
	userController := controllers.InitUserController(userUsecase)
	routerRouter := router.NewRouter(taskController, userController)
	return routerRouter
}
